#!/bin/bash

ENABLE_PROXY_HORIZON=0
ENABLE_PROXY_NOVA=0
ENABLE_PROXY_CINDRE=0
ENABLE_PROXY_NEUTRON=0
ENABLE_PROXY_KEYSTONE=0

ENABLE_JUDGE_HORIZON=0
ENABLE_JUDGE_CONTROLLER=0

ENBALE_SCHEDULE_HORIZON=0
ENBALE_SCHEDULE_CONTROLLER=0
ENBALE_SCHEDULE_KEYSTONE=0